### ISSUE TITLE
Unify environment variable prefixes from `KAFKAREST_` to `KAFKA_REST_`

### ISSUE THREAD

**Issue by cobolbaby** [confluentinc/kafka-rest#1195]
The environment variable prefixes of Kafka Rest Proxy are confusing. 

Could unify the coding style?

```
version: '2.3'
services:
  kafka-rest-proxy-1:
    image: registry.inventec/hub/confluentinc/cp-kafka-rest:5.5.11
    container_name: kafka-rest-proxy-1
    hostname: kafka-rest-proxy-1
    networks: 
      - net
    ports:
      - 8082:8082
      - 9992:9992
      - 9997:9997
    volumes:
      - /opt/kafka/jmx_exporter:/opt/kafka/jmx_exporter
      - /etc/localtime:/etc/localtime:ro
    environment:
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_HOST_NAME: kafka-rest-proxy-1
      KAFKA_REST_ID: kafka-rest-proxy-1
      KAFKA_REST_BOOTSTRAP_SERVERS: 192.168.16.116:19092,192.168.16.117:19092,192.168.16.118:19092
      KAFKAREST_HEAP_OPTS: "-Xms1g -Xmx1g -XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80"
      KAFKA_REST_PRODUCER_ACKS: all
      KAFKA_REST_PRODUCER_MAX_REQUEST_SIZE: 31457280
      KAFKA_REST_PRODUCER_RETRIES: 5
      KAFKA_REST_PRODUCER_RETRY_BACKOFF_MS: 2000
      KAFKA_REST_PRODUCER_COMPRESS_TYPE: none
      KAFKA_REST_PRODUCER_CLIENT_ID: kafka-rest-proxy-1
      # JMX Exporter
      KAFKA_REST_JMX_HOSTNAME: 10.99.169.116
      KAFKAREST_JMX_PORT: 9997
      KAFKAREST_OPTS: "-javaagent:/opt/kafka/jmx_exporter/jmx_prometheus_javaagent-0.15.0.jar=9992:/opt/kafka/jmx_exporter/kafka-rest-proxy-agent.yml"
    restart: always
    cpu_count: 2
    mem_limit: 2g
    logging:
      driver: 'json-file'
      options:
        max-size: 10m
    
networks:
  net:
    external: true
    name: infra
```
