### ISSUE TITLE
CORS - Response does not include Access-Control headers for GET request

### ISSUE THREAD

**Issue by Tuong-Nguyen** [confluentinc/kafka-rest#308]
I configure CORS settings in kafka-rest.properties file as follow:

access.control.allow.origin=*
access.control.allow.methos="GET,POST,PUT,DELETE"

The responses for POST - DELETE requests have Access-Control values in header. However, the GET requests does not have them and Browser may reject the response.

1- If the GET request does not contain Content-Type header, Browser accept the response.
2- If the GET request contains Content-Type header (ex: Content-Type: application/vnd.kafka.json.v2+json), Browser will reject the response.

Confluent Kafka REST should return Access-Control in response because it is configured in the kafka-rest.properties file.

**Comment by JozeFe** [comment]
same issue.

**Comment by qi4589746** [comment]
access.control.allow.origin=*
access.control.allow.methods=GET,POST,PUT,DELETE

**Comment by Devon-Peroutky** [comment]
Same issue. Is there any update?

**Comment by parallaxisjones** [comment]
same issue.

**Comment by ankitbansal** [comment]
Same issue. Also do we have support for Access-Control-Allow-Headers?

**Comment by cxk280** [comment]
Same issue here.

**Comment by churtado** [comment]
Same

**Comment by abeer-noor** [comment]
Same issue.

**Comment by Chrislevi** [comment]
Same issue. its already configured by default but im still getting CONNECTION ERROR through reverse-proxy(Traefik).. but directly it works..

@ewencp Can any of the devs comment?

**Comment by raymond-ong** [comment]
Thank you @jairsjunior 
To expound on it, I had to modify the file kafka-rest.properties inside 
../confluent-6.0.0/etc/kafka-rest folder, then restart the REST server.

**Comment by Caruso33** [comment]
For the ones using the docker-compose file that would correspond to the environment entries:
```
environment:
      ...
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,DELETE"
      KAFKA_REST_ACCESS_CONTROL_ALLOW_HEADERS: "origin,content-type,accept,authorization"
```
