### ISSUE TITLE
Error Code 50002 while trying to get records

### ISSUE THREAD

**Issue by andy2046** [confluentinc/kafka-rest#445]
Hi,
Got 50002 error while trying to get records, cannot see the consumer group created in kafka while doing `bin/kafka-consumer-groups.sh --bootstrap-server PLAINTEXT://bootstrap.kafka:9092 --list`

steps to produce the issue as shown below:

@ewencp  Even your advise is really appreciated, thanks.

```
➜  root curl -i -X POST -H "Content-Type: application/vnd.kafka.v2+json" -H "Accept: application/vnd.kafka.v2+json" \
    --data '{"records": [{ "key": "a2V5", "value": "Y29uZmx1ZW50" }, { "value": "bG9ncw==" }]}' \                                        
    http://$RESTIP:8082/topics/kafka-01  
HTTP/1.1 200 OK
Date: Mon, 09 Jul 2018 08:21:01 GMT
Content-Type: application/vnd.kafka.v2+json
Content-Length: 173
Server: Jetty(9.2.24.v20180105)

{"offsets":[{"partition":0,"offset":0,"error_code":null,"error":null},{"partition":0,"offset":1,"error_code":null,"error":null}],"key_schema_id":null,"value_schema_id":null}%    

➜  root curl -i -X POST -H "Content-Type: application/vnd.kafka.v2+json" -H "Accept: application/vnd.kafka.v2+json" \
    --data '{"name": "consumer-01", "format": "binary", "auto.offset.reset": "earliest"}' \
    http://$RESTIP:8082/consumers/consumer-group-03 
HTTP/1.1 200 OK
Date: Mon, 09 Jul 2018 08:21:32 GMT
Content-Type: application/vnd.kafka.v2+json
Content-Length: 118
Server: Jetty(9.2.24.v20180105)

{"instance_id":"consumer-01","base_uri":"http://xxx.xxx.xxx.xxx:8082/consumers/consumer-group-03/instances/consumer-01"}%                                                          

 ➜  root curl -i -X POST -H "Content-Type: application/vnd.kafka.v2+json" --data '{"topics":["kafka-01"]}' \          
    http://$RESTIP:8082/consumers/consumer-group-03/instances/consumer-01/subscription
HTTP/1.1 204 No Content
Date: Mon, 09 Jul 2018 08:22:04 GMT
Server: Jetty(9.2.24.v20180105)

➜  root curl -i -X GET -H "Accept: application/vnd.kafka.v2+json" \                                                  
    http://$RESTIP:8082/consumers/consumer-group-03/instances/consumer-01/records
HTTP/1.1 500 Internal Server Error
Date: Mon, 09 Jul 2018 08:22:19 GMT
Content-Type: application/vnd.kafka.v2+json
Content-Length: 650
Server: Jetty(9.2.24.v20180105)

{"error_code":50002,"message":"Kafka error: null io.confluent.rest.exceptions.RestServerErrorException: Kafka error: null\nio.confluent.rest.exceptions.RestServerErrorException: Kafka error: null\n\tat io.confluent.kafkarest.Errors.kafkaErrorException(Errors.java:188)\n\tat io.confluent.kafkarest.v2.KafkaConsumerManager$1.onCompletion(KafkaConsumerManager.java:295)\n\tat io.confluent.kafkarest.v2.KafkaConsumerReadTask.finish(KafkaConsumerReadTask.java:167)\n\tat io.confluent.kafkarest.v2.KafkaConsumerReadTask.doPartialRead(KafkaConsumerReadTask.java:153)\n\tat io.confluent.kafkarest.v2.KafkaConsumerWorker.run(KafkaConsumerWorker.java:112)\n"}%   
                                                          
```

yams file for deployment as shown below:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  namespace: kafka
  labels:
    app: zk
spec:
  serviceName: "zk-headless-svc"
  replicas: 1
  selector:
    matchLabels:
      app: zk
  template:
    metadata:
      labels:
        app: zk
        replicas: "1"
    spec:
      containers:
      - name: k8s-zk
        imagePullPolicy: IfNotPresent
        image: confluentinc/cp-zookeeper:4.1.1
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: zookeeper
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "broker"
  replicas: 1
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: kafka
      annotations:
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: broker
        image: confluentinc/cp-kafka:4.1.1
        env:
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        ports:
        - name: plaintext
          containerPort: 9092
        resources:
          requests:
            cpu: 800m
            memory: 2048Mi
        readinessProbe:
          tcpSocket:
            port: 9092
          timeoutSeconds: 1
        volumeMounts:
        - name: kafka
          mountPath: /var/lib/kafka
  volumeClaimTemplates:
  - metadata:
      name: kafka
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: kafka
      resources:
        requests:
          storage: 100Gi

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-proxy
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-rest
  template:
    metadata:
      labels:
        app: kafka-rest
    spec:
      containers:
      - name: kafka-rest
        image: confluentinc/cp-kafka-rest:4.1.1
        env:
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_REST_DEBUG
          value: "true"
        - name: KAFKA_REST_HOST_NAME
          value: "xxx.xxx.xxx.xxx"
        - name: KAFKA_REST_ID
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_REST_LISTENERS
          value: http://0.0.0.0:8082
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: PLAINTEXT://bootstrap.kafka:9092
        - name: KAFKA_REST_CONSUMER_THREADS
          value: "12"
        - name: KAFKA_REST_PRODUCER_THREADS
          value: "6"
        - name: KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS
          value: "3000"
        - name: KAFKA_REST_CONSUMER_REQUEST_MAX_BYTES
          value: "300000"
        - name: KAFKA_REST_CONSUMER_INSTANCE_TIMEOUT_MS
          value: "300000"
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
        ports:
        - containerPort: 8082
```
