### ISSUE TITLE
SSL handshake fails

### ISSUE THREAD

**Issue by lucasmarfe** [confluentinc/kafka-rest#572]
I have a kafka cluster on docker using confluent images. I am using docker-compose to build the containers.

When I tried to run the container it starts but can't communicate with any broker due to SSL handshake failed. I don't know if I miss some configuration

[kafka-admin-client-thread | adminclient-1] ERROR org.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Connection to node -3 (/XXX:19092) failed authentication due to: SSL handshake failed

My Kafka brokers are configured as follows:

kafka1:

> image: confluentinc/cp-kafka:5.2.2
container_name: kafka1
ports:
  - "19092:19092"
environment:
  KAFKA_BROKER_ID: 1
  KAFKA_ZOOKEEPER_CONNECT: XXX:12181,XXX:12181,XXX:12181
  KAFKA_ADVERTISED_LISTENERS: SSL://XXXX:19092
  KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker1.keystore.jks
  KAFKA_SSL_KEYSTORE_CREDENTIALS: broker1_keystore_creds
  KAFKA_SSL_KEY_CREDENTIALS: broker1_sslkey_creds
  KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker1.truststore.jks
  KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker1_truststore_creds
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
  KAFKA_SSL_CLIENT_AUTH: required
  KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
  KAFKA_SECURITY_PROTOCOL: SSL
volumes:
  - ./../../secrets:/etc/kafka/secrets
I am trying to bring a Confluent REST Proxy API into another container using the configurations:

kafka-rest-proxy:

image: confluentinc/cp-kafka-rest:5.2.2
hostname: kafka-rest-proxy
ports:
  - "18082:18082"
environment:
  KAFKA_REST_LISTENERS: "http://0.0.0.0:18082"
  KAFKA_REST_ZOOKEEPER_CONNECT: XXX:12181,XXX:12181,XXX:12181
  KAFKA_REST_HOST_NAME: kafka-rest-proxy
  KAFKA_REST_BOOTSTRAP_SERVERS: SSL://XXX:19092,SSL://XXX:19092,SSL://XXX:19092
  KAFKA_REST_CLIENT_SECURITY_PROTOCOL: SSL
  KAFKA_REST_CLIENT_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.broker1.keystore.jks
  KAFKA_REST_CLIENT_SSL_KEYSTORE_PASSWORD: XXX     
  KAFKA_REST_CLIENT_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.broker1.truststore.jks
  KAFKA_REST_CLIENT_SSL_TRUSTSTORE_PASSWORD: XXX
  KAFKA_REST_CLIENT_SSL_KEY_PASSWORD: XXX 
  KAFKA_REST_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.producer.keystore.jks
  KAFKA_REST_SSL_KEYSTORE_PASSWORD: XXX
  KAFKA_REST_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.producer.truststore.jks
  KAFKA_REST_SSL_TRUSTSTORE_PASSWORD: XXX
volumes:
  - ./../../secrets:/etc/kafka/secrets

**Comment by kaushiksrinivas** [comment]
Are u still facing this issue ? 
Looks like, the certificates of kafka has the problem.
kafka certificates must have the name with which it is accessed by the kafka rest added as part of the CommonName(CN) or the SAN (subject alternative names).
else client(Kafka rest in this case) upon handshake will compare the domain it is trying to connect to and the aliases presented by the kafka in SSL handshake via CN or SAN and fails if a matching entry is not found.

**Comment by kbreidenbachRN** [comment]
I am seeing this same error. It appears that the error is caused because the only the IP address of the kafka-rest-proxy is being transmitted and not the hostname:

```
[2020-08-28 03:47:00,332] INFO [SocketServer brokerId=1] Failed authentication with /192.168.112.5 (SSL handshake failed) (org.apache.kafka.common.network.Selector)
```

My kafka config is:
```
  kafka1:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka1
    command: "bash -c 'if [ ! -f /etc/kafka/secrets/kafka1.keystore.jks ]; then echo \"ERROR: Did not find SSL certificates in /etc/kafka/secrets/\" && exit 1 ; else /etc/confluent/docker/run ; fi'"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_SSL://kafka1:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_SSL:SSL,LISTENER_DOCKER_EXTERNAL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_SSL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SASL_ENABLED_MECHANISMS: SSL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SSL_KEYSTORE_FILENAME: kafka1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: creds
      KAFKA_SSL_KEY_CREDENTIALS: creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: creds
      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM:
    volumes:
      - ./full-stack/kafka1/data:/var/lib/kafka/data
      - ./keys:/etc/kafka/secrets
    depends_on:
      - zoo1
```

and kafka-rest-proxy config is:
```
  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:5.5.1
    hostname: kafka-rest-proxy
    ports:
      - "8082:8082"
    volumes:
      - ./keys:/etc/kafka/secrets
    environment:
      #KAFKA_REST_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: SSL://kafka1:19093
      KAFKA_REST_CLIENT_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka-rest-proxy.truststore.jks
      KAFKA_REST_CLIENT_SSL_TRUSTSTORE_PASSWORD: testadmin
      KAFKA_REST_CLIENT_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka-rest-proxy.keystore.jks
      KAFKA_REST_CLIENT_SSL_KEYSTORE_PASSWORD: testadmin
      KAFKA_REST_CLIENT_SSL_KEY_PASSWORD: testadmin
    depends_on:
      - zoo1
      - kafka1
      - kafka-schema-registry
```

The only thing I can think of is there is a problem where the hostname (in this case `kafka-rest-proxy`) is not being transmitted when trying to connect
