### ISSUE TITLE
First messages got lost when sending through REST API on startup

### ISSUE THREAD

**Issue by dmitriibundin** [confluentinc/kafka-rest#752]
`docker-compose.yml`:

```
version: "3.8"
services:
    zookeeper:
        image: 'confluentinc/cp-zookeeper:6.0.0'
        network_mode: "host"
        environment:
            - ZOOKEEPER_CLIENT_PORT=32181
            - ZOOKEEPER_TICK_TIME=2000
            - ZOOKEEPER_SYNC_LIMIT=2

    kafka:
        image: 'confluentinc/cp-kafka:6.0.0'
        depends_on:
            - zookeeper
        network_mode: "host"
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=localhost:32181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092
            - KAFKA_BROKER_ID=2
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

    schema_registry:
        image: 'confluentinc/cp-schema-registry:6.0.0'
        depends_on:
            - kafka
        network_mode: "host"
        environment:
            - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=localhost:32181
            - SCHEMA_REGISTRY_HOST_NAME=localhost
            - SCHEMA_REGISTRY_LISTENERS=http://localhost:8081
            - SCHEMA_REGISTRY_DEBUG=true

    kafka_rest:
        image: 'confluentinc/cp-kafka-rest:6.0.0'
        depends_on:
            - schema_registry
        network_mode: "host"
        environment:
            - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://localhost:29092
            - KAFKA_REST_ZOOKEEPER_CONNECT=localhost:32181
            - KAFKA_REST_LISTENERS=http://localhost:8082
            - KAFKA_REST_SCHEMA_REGISTRY_URL=http://localhost:8081


    kafka_create_topics:      
        image: 'confluentinc/cp-kafka:6.0.0'
        depends_on:
            - kafka_rest
        network_mode: "host"
        command: "bash -c 'cub kafka-ready -b localhost:29092 1 20 && \
                  kafka-topics --create --if-not-exists --zookeeper localhost:32181 --partitions 2 --replication-factor 1 --topic some-topic'"
```

API calls to execute:

```
curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" 'http://localhost:8082/consumers/grps' -d '{"name": "c1"}'
curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" 'http://localhost:8082/consumers/grps/instances/c1/subscription' -d '{"topics": ["some-topic"]}'

#Send 2 records and then consume 
curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" 'http://localhost:8082/topics/some-topic' -d '{"records":[{"value":"str1"},{"value":"str2"}]}'
curl 'http://localhost:8082/consumers/grps/instances/c1/records' | jq

#Same as above. Send 2 records and then consume
curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" 'http://localhost:8082/topics/some-topic' -d '{"records":[{"value":"str1"},{"value":"str2"}]}'
curl 'http://localhost:8082/consumers/grps/instances/c1/records' | jq
```

**Expected output**:

```
[                                                                                                                                                                                                                  
  {                                                                                                                                                                                                                
    "topic": "some-topic",                                                                                                                                                                                         
    "key": null,                                                                                                                                                                                                   
    "value": "InN0cjEi",                                                                                                                                                                                           
    "partition": 1,                                                                                                                                                                                                
    "offset": 0                                                                                                                                                                                                    
  },                                                                                                                                                                                                               
  {                                                                                                                                                                                                                
    "topic": "some-topic",                                                                                                                                                                                         
    "key": null,                                                                                                                                                                                                   
    "value": "InN0cjIi",                                                                                                                                                                                           
    "partition": 1,                                                                                                                                                                                                
    "offset": 1                                                                                                                                                                                                    
  }                                                                                                                                                                                                                
] 
[                                                                                                                                                                                                                  
  {                                                                                                                                                                                                                
    "topic": "some-topic",                                                                                                                                                                                         
    "key": null,                                                                                                                                                                                                   
    "value": "InN0cjEi",                                                                                                                                                                                           
    "partition": 1,                                                                                                                                                                                                
    "offset": 0                                                                                                                                                                                                    
  },                                                                                                                                                                                                               
  {                                                                                                                                                                                                                
    "topic": "some-topic",                                                                                                                                                                                         
    "key": null,                                                                                                                                                                                                   
    "value": "InN0cjIi",                                                                                                                                                                                           
    "partition": 1,                                                                                                                                                                                                
    "offset": 1                                                                                                                                                                                                    
  }                                                                                                                                                                                                                
] 
```

**Actual output:**

```
[]
[                                                                                                                                                                                                                  
  {                                                                                                                                                                                                                
    "topic": "some-topic",                                                                                                                                                                                         
    "key": null,                                                                                                                                                                                                   
    "value": "InN0cjEi",                                                                                                                                                                                           
    "partition": 1,                                                                                                                                                                                                
    "offset": 0                                                                                                                                                                                                    
  },                                                                                                                                                                                                               
  {                                                                                                                                                                                                                
    "topic": "some-topic",                                                                                                                                                                                         
    "key": null,                                                                                                                                                                                                   
    "value": "InN0cjIi",                                                                                                                                                                                           
    "partition": 1,                                                                                                                                                                                                
    "offset": 1                                                                                                                                                                                                    
  }                                                                                                                                                                                                                
]
```

As can be seen the actual output contains an empty list instead of one containing the actual data.
