### ISSUE TITLE
Neither auto.commit.enable nor enable.auto.commit works

### ISSUE THREAD

**Issue by dmitriibundin** [confluentinc/kafka-rest#753]
**docker-compose.yml**:

```
version: "3.8"
services:
    zookeeper:
        image: 'confluentinc/cp-zookeeper:6.0.0'
        network_mode: "host"
        environment:
            - ZOOKEEPER_CLIENT_PORT=32181
            - ZOOKEEPER_TICK_TIME=2000
            - ZOOKEEPER_SYNC_LIMIT=2

    kafka:
        image: 'confluentinc/cp-kafka:6.0.0'
        depends_on:
            - zookeeper
        network_mode: "host"
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=localhost:32181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092
            - KAFKA_BROKER_ID=2
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

    schema_registry:
        image: 'confluentinc/cp-schema-registry:6.0.0'
        depends_on:
            - kafka
        network_mode: "host"
        environment:
            - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=localhost:32181
            - SCHEMA_REGISTRY_HOST_NAME=localhost
            - SCHEMA_REGISTRY_LISTENERS=http://localhost:8081
            - SCHEMA_REGISTRY_DEBUG=true

    kafka_rest:
        image: 'confluentinc/cp-kafka-rest:6.0.0'
        depends_on:
            - schema_registry
        network_mode: "host"
        environment:
            - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://localhost:29092
            - KAFKA_REST_ZOOKEEPER_CONNECT=localhost:32181
            - KAFKA_REST_LISTENERS=http://localhost:8082
            - KAFKA_REST_SCHEMA_REGISTRY_URL=http://localhost:8081


    kafka_create_topics:      
        image: 'confluentinc/cp-kafka:6.0.0'
        depends_on:
            - kafka_rest
        network_mode: "host"
        command: "bash -c 'cub kafka-ready -b localhost:29092 1 20 && \
                  kafka-topics --create --if-not-exists --zookeeper localhost:32181 --partitions 2 --replication-factor 1 --topic some-topic'"

```

**API requests**:

```
curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" 'http://localhost:8082/consumers/grps' -d '{"name": "c1", "auto.offset.reset":"earliest", "auto.commit.enable":"false"}'
curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" 'http://localhost:8082/consumers/grps/instances/c1/subscription' -d '{"topics": ["some-topic"]}'
curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" 'http://localhost:8082/topics/some-topic' -d '{"records":[{"value":"str"}]}'
curl 'http://localhost:8082/consumers/grps/instances/c1/records' | jq
curl 'http://localhost:8082/consumers/grps/instances/c1/records' | jq
curl 'http://localhost:8082/consumers/grps/instances/c1/records' | jq

```

**Actual output**:
```
[]
[                                                                                                                                                                                                                  
  {                                                                                                                                                                                                                
    "topic": "some-topic",                                                                                                                                                                                         
    "key": null,                                                                                                                                                                                                   
    "value": "InN0ciI=",                                                                                                                                                                                           
    "partition": 1,                                                                                                                                                                                                
    "offset": 0                                                                                                                                                                                                    
  }                                                                                                                                                                                                                
]
[]
```

**Expected output**:

```
[                                                                                                                                                                                                                  
  {                                                                                                                                                                                                                
    "topic": "some-topic",                                                                                                                                                                                         
    "key": null,                                                                                                                                                                                                   
    "value": "InN0ciI=",                                                                                                                                                                                           
    "partition": 1,                                                                                                                                                                                                
    "offset": 0                                                                                                                                                                                                    
  }                                                                                                                                                                                                                
]
[                                                                                                                                                                                                                  
  {                                                                                                                                                                                                                
    "topic": "some-topic",                                                                                                                                                                                         
    "key": null,                                                                                                                                                                                                   
    "value": "InN0ciI=",                                                                                                                                                                                           
    "partition": 1,                                                                                                                                                                                                
    "offset": 0                                                                                                                                                                                                    
  }                                                                                                                                                                                                                
]
[                                                                                                                                                                                                                  
  {                                                                                                                                                                                                                
    "topic": "some-topic",                                                                                                                                                                                         
    "key": null,                                                                                                                                                                                                   
    "value": "InN0ciI=",                                                                                                                                                                                           
    "partition": 1,                                                                                                                                                                                                
    "offset": 0                                                                                                                                                                                                    
  }                                                                                                                                                                                                                
]
```

Since `auto.commit.enable` is turned off and no manual commit was done the same message should have been delivered 3 times.
