### ISSUE TITLE
Cannot have 2 consumers on the same rest proxy

### ISSUE THREAD

**Issue by dmitriibundin** [confluentinc/kafka-rest#760]
**Description:** When creating 2 consumers via REST API the second one is not created until the first one time outs. Retrying the creation of the two succeeds though.

**docker-compose.yml**
```
version: "3.8"
services:
    zookeeper:
        image: 'confluentinc/cp-zookeeper:6.0.0'
        network_mode: "host"
        environment:
            - ZOOKEEPER_CLIENT_PORT=32181
            - ZOOKEEPER_TICK_TIME=2000
            - ZOOKEEPER_SYNC_LIMIT=2

    kafka:
        image: 'confluentinc/cp-kafka:6.0.0'
        depends_on:
            - zookeeper
        network_mode: "host"
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=localhost:32181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092
            - KAFKA_BROKER_ID=2
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

    schema_registry:
        image: 'confluentinc/cp-schema-registry:6.0.0'
        depends_on:
            - kafka
        network_mode: "host"
        environment:
            - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=localhost:32181
            - SCHEMA_REGISTRY_HOST_NAME=localhost
            - SCHEMA_REGISTRY_LISTENERS=http://localhost:8081
            - SCHEMA_REGISTRY_DEBUG=true

    kafka_rest:
        image: 'confluentinc/cp-kafka-rest:6.0.0'
        depends_on:
            - schema_registry
        network_mode: "host"
        environment:
            - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://localhost:29092
            - KAFKA_REST_ZOOKEEPER_CONNECT=localhost:32181
            - KAFKA_REST_LISTENERS=http://localhost:8082
            - KAFKA_REST_SCHEMA_REGISTRY_URL=http://localhost:8081


    kafka_create_topics:      
        image: 'confluentinc/cp-kafka:6.0.0'
        depends_on:
            - kafka_rest
        network_mode: "host"
        command: "bash -c 'cub kafka-ready -b localhost:29092 1 20 && \
                  kafka-topics --create --if-not-exists --zookeeper localhost:32181 --partitions 2 --replication-factor 1 --topic some-topic'"

``` 

**REST API calls:**
```
# creating c1 consumer
curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" 'http://localhost:8082/consumers/grps' -d '{"name": "c1", "auto.offset.reset":"earliest", "auto.commit.enable":"false"}'
curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" 'http://localhost:8082/consumers/grps/instances/c1/subscription' -d '{"topics": ["some-topic"]}'
curl -H "Accept: application/vnd.kafka.binary.v2+json" 'http://localhost:8082/consumers/grps/instances/c1/records' | jq

# creating c2 consumer
curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" 'http://localhost:8082/consumers/grps' -d '{"name": "c2", "auto.offset.reset":"earliest", "auto.commit.enable":"false"}'
curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" 'http://localhost:8082/consumers/grps/instances/c2/subscription' -d '{"topics": ["some-topic"]}'
curl -H "Accept: application/vnd.kafka.binary.v2+json" 'http://localhost:8082/consumers/grps/instances/c2/records' | jq
```

**Expected behavior:**

`$ kafka-consumer-groups --describe --bootstrap-server localhost:29092 --group grps`

```
GROUP           TOPIC            PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                          HOST            CLIENT-ID
grps            some-topic 0          -               0               -               consumer-grps-1-80493a7b-0a82-48a4-855d-f709bbd1a2e7 /127.0.0.1      consumer-grps-1
grps            some-topic 1          -               0               -               consumer-grps-1-80493a7b-0a82-48a4-855d-f709bbd1a2e7 /127.0.0.1      consumer-grps-1
grps            some-topic 2          -               0               -               consumer-grps-2-bb71ee4d-d7f7-4f4e-863c-265898333625 /127.0.0.1      consumer-grps-2
grps            some-topic 3          -               0               -               consumer-grps-2-bb71ee4d-d7f7-4f4e-863c-265898333625 /127.0.0.1      consumer-grps-2

```

**Actual beahvior:**

Rebalancing is triggered until the first consumer (`c1`) timesout (5 min by default). There logs of rest proxy:

```
kafka_rest_1           | [2020-10-12 08:54:17,531] INFO [Consumer clientId=consumer-grps-2, groupId=grps] Cluster ID: qkEVuGzfQEmQakHAR-2BFw (org.apache.kafka.clients.Metadata)
kafka_rest_1           | [2020-10-12 08:54:17,532] INFO [Consumer clientId=consumer-grps-2, groupId=grps] Discovered group coordinator localhost:29092 (id: 2147483645 rack: null) (org.apache.kafka.clients.consum
er.internals.AbstractCoordinator)
kafka_rest_1           | [2020-10-12 08:54:17,532] INFO [Consumer clientId=consumer-grps-2, groupId=grps] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
kafka_rest_1           | [2020-10-12 08:54:17,536] INFO [Consumer clientId=consumer-grps-2, groupId=grps] Join group failed with org.apache.kafka.common.errors.MemberIdRequiredException: The group member needs t
o have a valid member id before actually entering a consumer group. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
kafka_rest_1           | [2020-10-12 08:54:17,536] INFO [Consumer clientId=consumer-grps-2, groupId=grps] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
kafka_1                | [2020-10-12 08:54:17,537] INFO [GroupCoordinator 2]: Preparing to rebalance group grps in state PreparingRebalance with old generation 1 (__consumer_offsets-14) (reason: Adding new membe
r consumer-grps-2-2e97888d-87ea-4c03-b8db-cc03cf61b5c0 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
kafka_rest_1           | [2020-10-12 08:54:18,208] INFO [Consumer clientId=consumer-grps-1, groupId=grps] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.Abstr
actCoordinator)
kafka_rest_1           | [2020-10-12 08:54:21,226] INFO [Consumer clientId=consumer-grps-1, groupId=grps] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.Abstr
actCoordinator)
kafka_rest_1           | [2020-10-12 08:54:24,243] INFO [Consumer clientId=consumer-grps-1, groupId=grps] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.Abstr
actCoordinator)
kafka_rest_1           | [2020-10-12 08:54:27,259] INFO [Consumer clientId=consumer-grps-1, groupId=grps] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.Abstr
actCoordinator)
kafka_rest_1           | [2020-10-12 08:54:30,274] INFO [Consumer clientId=consumer-grps-1, groupId=grps] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.Abstr
actCoordinator)
kafka_rest_1           | [2020-10-12 08:54:33,289] INFO [Consumer clientId=consumer-grps-1, groupId=grps] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.Abstr
actCoordinator)
kafka_rest_1           | [2020-10-12 08:54:36,303] INFO [Consumer clientId=consumer-grps-1, groupId=grps] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.Abstr
actCoordinator)
kafka_rest_1           | [2020-10-12 08:54:39,316] INFO [Consumer clientId=consumer-grps-1, groupId=grps] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.Abstr
actCoordinator)
kafka_rest_1           | [2020-10-12 08:54:42,328] INFO [Consumer clientId=consumer-grps-1, groupId=grps] Attempt to heartbeat failed since group is rebalancing (org.apache.kafka.clients.consumer.internals.Abstr
actCoordinator)

```

After the fisrt consumer times out the second one takes over all the four partitions:

`$ kafka-consumer-groups --describe --bootstrap-server localhost:29092 --group grps`

```
GROUP           TOPIC            PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                          HOST            CLIENT-ID
grps            some-topic 0          0               0               0               consumer-grps-1-aaf0a926-af61-4066-8d02-50e992af94d4 /127.0.0.1      consumer-grps-1
grps            some-topic 1          0               0               0               consumer-grps-1-aaf0a926-af61-4066-8d02-50e992af94d4 /127.0.0.1      consumer-grps-1
grps            some-topic 2          0               0               0               consumer-grps-1-aaf0a926-af61-4066-8d02-50e992af94d4 /127.0.0.1      consumer-grps-1
grps            some-topic 3          0               0               0               consumer-grps-1-aaf0a926-af61-4066-8d02-50e992af94d4 /127.0.0.1      consumer-grps-1
```
